apiVersion: v1
kind: Service
metadata:
  labels:
    name: pgadmin
    app: pgadmin
  name: pgadmin
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
  selector:
    name: pgadmin
    app: pgadmin