apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pgadmin
      app: pgadmin
  template:
    metadata:
      labels:
        name: pgadmin
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4:6.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config  
          volumeMounts:
            - mountPath: /var/tmp/pgadmin
              name: pgadminstorage       
      volumes:
        - name: pgadminstorage
          persistentVolumeClaim:
            claimName: api-datamodels-pvc 

     