apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomysql
labels:
    app: ecomysql  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecomysql
  template:
    metadata:
      labels:
        app: ecomysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306         
              protocol: TCP
          
     