apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapi
      app: enmeter
  template:
    metadata:
      labels:
        name: webapi
        app: enmeter
    spec:
      containers:
        - name: python
          image: devnawed/python-flask:v3.2
          ports:
            - containerPort: 5000         
              name: http
              protocol: TCP
          
          
               