apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
      app: enmeter
  template:
    metadata:
      labels:
        name: frontend
        app: enmeter
    spec:
      containers:
        - name: angular
          image: ecometric.eastus.cloudapp.azure.com:83/ecometric-angular:1.0.3237
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: registrycred