apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: "admin@jub.com"
  PGADMIN_DEFAULT_PASSWORD: "Jubl@123!@#"
  PGADMIN_PORT: "80"