apiVersion: v1
kind: Service
metadata:
  labels:
    name: pgadmin
    app: pgadmin
  name: pgadmin
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30200
  selector:
    name: pgadmin
    app: pgadmin