apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadminwos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pgadminwos
      app: pgadmin
  template:
    metadata:
      labels:
        name: pgadminwos
        app: pgadmin
    spec:
      containers:
        - name: pgadminwos4
          image: dpage/pgadmin4:5.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pgadmin-config  

     