apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresthirteen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresthirteen
  template:
    metadata:
      labels:
        app: postgresthirteen
    spec:
      containers:
        - name: postgresthirteen
          image: postgres:13.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgresthirteen-pv-claim

          