kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresthirteen-pv-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/jub_db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresthirteen-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi