---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: resenseui-lb
    app: resensepoc
  name: resenseui-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    name: resenseui
    app: resensepoc     