kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile # This storage class is created default in AKS. It is a sample file don't run it
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS
allowVolumeExpansion: true  