apiVersion: v1
kind: Service
metadata:
  labels:
    name: gitlab-angular
    app: angular
  name: gitlab-angularlb
spec:
  type: LoadBalancer
  ports:
  - name: gitlab-angular
    port: 80
    protocol: TCP
  selector:
    name: gitlab-angular
    app: angular