apiVersion: v1
kind: Service
metadata:
  labels:
    name: angular
    app: angular
  name: angular
spec:
  type: ClusterIP
  ports:
  - name: angular
    port: 80
    protocol: TCP
  selector:
    name: angular
    app: angular