apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
    app: enmeter
  name: frontend-lb
spec:
  type: LoadBalancer
  ports:
  - name: angular
    port: 80
    protocol: TCP
  selector:
    name: frontend
    app: enmeter