apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
    app: enmeter
  name: frontend
spec:
  type: ClusterIP
  ports:
  - name: angular
    port: 80
    protocol: TCP
  selector:
    name: frontend
    app: enmeter