apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq