apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    protocol: TCP
    name: msgqueue
  - port: 15672
    protocol: TCP
    name: management  
  selector:
    app: taskQueue
    component: rabbitmq