apiVersion: apps/v1
kind: Deployment
metadata:
  name: datamodelsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: datamodelsapi
      app: enmeter
  template:
    metadata:
      labels:
        name: datamodelsapi
        app: enmeter
    spec:
      containers:
        - name: datamodels
          image: devnawed/ecometric-model:v1.2
          ports:
            - containerPort: 5001         
              name: http
              protocol: TCP
          
          
               