apiVersion: v1
kind: Service
metadata:
  name: datamodelsapi
  labels:
    name: datamodelsapi
    app: enmeter
spec:
  selector:
    name: datamodelsapi 
    app: enmeter
  type: NodePort
  ports:
   - port: 5001
     name: http
     targetPort: 5001
     protocol: TCP