apiVersion: v1
kind: Service
metadata:
  labels:
    name: datamodelsapi-lb
    app: enmeter
  name: datamodelsapi-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5001
    protocol: TCP
  selector:
    name: datamodelsapi 
    app: enmeter