apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecometric-datamodels-pv-claim
spec:
  storageClassName: datamodels-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
