apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecometric-datamodels-pv-volume
  labels:
    type: local
spec:
  storageClassName: datamodels-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ecometric-datamodels"
