apiVersion: v1
kind: Pod
metadata:
  name: private-reg-1
spec:
  containers:
  - name: private-azure-ubuntu
    # image: cloud.canister.io:5000/nawed005/ecometric-ui:v1.0
    image: ecometric.eastus.cloudapp.azure.com:83/ecometric-angular:1.0.3237
  imagePullSecrets:
  - name: registrycred

