apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecodb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ecodb
      app: enmeter
  template:
    metadata:
      labels:
        name: ecodb
        app: enmeter
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.22
          ports:
            - containerPort: 3306         
              protocol: TCP
          env: 
            - name: "MYSQL_ROOT_PASSWORD"
              value: "password"
          
     