apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecometric-api-pv-volume
  labels:
    type: local
spec:
  storageClassName: api-storage
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ecometric-rest-api"
