apiVersion: v1
kind: Service
metadata:
  labels:
    name: webapi-lb
    app: enmeter
  name: webapi-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    protocol: TCP
  selector:
    name: webapi 
    app: enmeter