apiVersion: v1
kind: Service
metadata:
  labels:
    name: demoui-lb
    app: demoui
  name: demoui-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    name: demoui
    app: demoui