apiVersion: v1
kind: Service
metadata:
  name: resense-api-service
  labels:
    name: resenseapi
    app: resensepoc
spec:
  type: ClusterIP
  selector:
    name: resenseapi
    app: resensepoc
  ports:
   - port: 5000
     name: http
     protocol: TCP