apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webui
      app: jubwebui
  template:
    metadata:
      labels:
        name: webui
        app: jubwebui
    spec:
      containers:
        - name: angularui
          #image: 10.5.4.55:32000/jubui:2.1
          #image: 172.16.1.225:83/jubui:1.0.8141
          image: 10.5.4.79:83/jubui:5.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80         
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: regcred        
          
          
               