apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-lb
    app: jubilant
  name: api-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    protocol: TCP
  selector:
    name: api 
    app: jubilant