apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-np
    app: jubilant
  name: api-np
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    nodePort: 30000
    protocol: TCP
  selector:
    name: api
    app: jubilant