apiVersion: v1
kind: Service
metadata:
  labels:
    name: datamodels-lb
    app: jubilant
  name: datamodels-lb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5001
    protocol: TCP
  selector:
    name: datamodels 
    app: jubilant