apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: incemental-data-forecast-ingredient-indent
spec:
  #schedule: "0 00-14 * * *"
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: jub-datamodels-pv-storage
              persistentVolumeClaim:
                claimName: datamodels-pv-claim
          containers:
            - name: con-incemental-data-forecast-ingredient-indent
              #image: 172.16.1.225:83/jubdatamodels:7.7
              image: 10.5.6.34:83/jubdatamodels:9.5
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /app/data
                  name: jub-datamodels-pv-storage 
              command:
              - /bin/sh
              - -c
              - "python transform.py"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
