apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: transformincementaldata
spec:
  #schedule: "*/59 0-13 * * *"
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: jub-datamodels-pv-storage
              persistentVolumeClaim:
                claimName: datamodels-pv-claim
          containers:
            - name: contransformincementaldata
              image: 172.16.1.225:83/jubdatamodels:5.7
              #image: 10.5.6.34:83/jubdatamodels:5.1
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /app/data
                  name: jub-datamodels-pv-storage 
              command:
              - /bin/sh
              - -c
              - "python transform.py"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: regcred
