apiVersion: "v1"
kind: Pod
metadata:
  name: webapi
  labels:
    name: webapi
    app: enmeter
spec:
  containers:
    - name: python
      image: devnawed/python-flask
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP  
      env:
        - name: DB_HOST
          value: ecodb                    